#AUTHORIZATION
postLoginApi = "/authserver/api/authentication/accesstoken"
getValidateTokenApi = "/authserver/api/Authentication/ValidateToken"
#PRODUCT
getBulkPriceSearchResultApi = "/api/Product/BulkPriceSearch"
postPublishApi = "/api/Product/EditBulkPrice"
getProductMasterDataApi = "/api/Product/MasterData"
getProductBaseGroupListApi = "/api/ProductBaseGroup/ProductBaseGroupList"
getManufacturersApi = "/api/Company/ManufacturerList"
getDisplayNameApi = "/api/Product/DisplayName"
postSaveApi = "/api/Product/SaveProduct"
getProductSearchApi = "/api/Product/Search"
getARFNoteApi = "/api/Articles/ArfNote"
getPharmacyListApi = "/api/Company/PharmacyList"
getStateListApi = "/api/State/StateList"
getCompanyListApi = "/api/Company/CompanyList"
getDistributorListApi = "/api/Company/DistributorList"
getConsultProductApi = "/api/Product/ConsultProduct"
getCarrierServiceListApi = "/api/CarrierService/CarrierServiceList"
getDistributorPharmacyApi = "/api/Company/DistributorPharmacy"
getProductApi = "/api/Product/"
putProductApi = "/api/Product/"
getProductStoreFrontMasterDataApi = "/api/Product/StorefrontMasterData"
getStorefrontProductApi = "/api/Product/StorefrontProduct"
getSearchProductReceiptLetterApi = "/api/Product/SearchProductReceiptLetter"
getStorefrontConsultProductApi = "/api/Product/StorefrontConsultProduct"
getValidateReceiptLetterApi = "/api/Product/ValidateReceiptLetterName"
#STOREFRONT
getStoreFrontMasterDataApi = "/api/Storefront/MasterData"
getStoreFrontValidateSSLUrlApi = "/api/Storefront/ValidateSSLUrl"
getStoreFrontListApi = "/api/Storefront/StorefrontList"
getActiveStoreFrontListApi = "/api/Storefront/ActiveStorefrontList"
getImportStorefrontSettingsApi = "/api/Storefront/ImportStorefrontSettings"
getManageStorefrontApi = "/api/Storefront/ManageStorefront"
postStorefrontSaveApi = "/api/Storefront/SaveStorefront"
postStorefrontImagesSaveApi = "/api/Storefront/SaveStorefrontImage/"
getStorefrontApi = "/api/Storefront/"
putStorefrontApi = "/api/Storefront/"
getStorefrontValidateEmailLinkDomain = "/api/Storefront/ValidateEmailLinkDomain"
getSearchStorefrontProductApi = "/api/Storefront/SearchStorefrontProduct"
#VISIT TYPE
getStorefrontPresetListApi = "/api/VisitType/StorefrontPresetList"
getStorefrontPreset = "/api/VisitType/GetVisitTypePresetConfigByPresetId/"
getVisitTypePreset = "/api/VisitType/GetVisitTypePreset"
postVisitTypePreset = "/api/VisitType/SaveVisitTypePreset"
putVisitTypePreset = "/api/VisitType/"
